site_name: Be The Hero
theme:
  logo: https://cdn-icons-png.flaticon.com/512/2374/2374370.png
  favicon: https://cdn-icons-png.flaticon.com/512/2374/2374370.png
  name: material
  language: "pt"
  features:
    navigation.top
    - navigation.sections
    - toc.integrate

  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      primary: indigo
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      primary: indigo
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

nav:
  - Sobre: index.md
  - Planejamento: planning.md
  - Levantamento de Requisitos:
    - Técnicas:
      - Brainstorming: requirements/brainstorming.md
      - MoSCoW: requirements/moscow.md
    - Personas: requirements/personas.md
    - Requisitos Levantados: requirements/requirements.md
  - Modelagem de requisitos:
    - Caso de Uso: requirements/use-case.md

plugins:
  - search:
      lang: pt
      lang: en

copyright: Copyright &copy; 2022 Wesley & Lucas

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/bw3sley
      name: bw3sley on GitHub
    - icon: fontawesome/brands/github
      link: https://github.com/loskafaria1757
      name: loskafaria1757 on GitHub

extra_css:
  - stylesheets/extra.css