site_name: Be The Hero
theme:
  logo: assets/logo.svg
  favicon: assets/logo.svg
  name: material
  language: "pt"
  features:
    navigation.top
    - navigation.sections
    - toc.integrate

  palette:
      accent: 

extra_css:
  - global.css

nav:
  - Sobre: index.md
  - Planejamento: planning.md
  - Levantamento de Requisitos:
    - Técnicas:
      - Brainstorming: requirements/brainstorming.md
      - MoSCoW: requirements/moscow.md
    - Personas: requirements/personas.md
    - Requisitos Levantados: requirements/requirements.md
  - Modelagem de requisitos:
    - Caso de Uso: requirements/use-case.md
  - Protótipo: 
    - Wireframe: prototype/wireframe.md
    - Protótipo alta fidelidade: prototype/prototype.md

plugins:
  - search:
      lang: pt
      lang: en

copyright: Copyright &copy; 2022 Wesley & Lucas

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/bw3sley
      name: bw3sley on GitHub
    - icon: fontawesome/brands/github
      link: https://github.com/loskafaria1757
      name: loskafaria1757 on GitHub